### ISSUE TITLE
Rank bot isn't working!

### ISSUE THREAD

**Issue by CakePlayz** [CookieHax/RankingAPI#6]
I did all of the steps correctly and when I put in the key hoping for a response as I pressed enter, My response was null. Please help me because I trusted you.

**Comment by Noah-Haf** [comment]
Please check your Heroku Logs.

**Comment by Noah-Haf** [comment]
This system fully works, so your doing something wrong, check this post here for more information: https://forums.thecookie.dev/t/my-rank-bot-isnt-working/1516/2
